version: "3.8"

services:

  sample-app:
    build: ./sample-app
    container_name: sample-app
    volumes:
      - ./sample-app:/app
      - ./logs:/var/log
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml
    command: -config.file=/etc/loki/loki.yml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml
      - ./logs:/var/log
    command: -config.file=/etc/promtail/promtail.yml

  tempo:
    image: grafana/tempo:latest
    volumes:
      - ./tempo/tempo.yml:/etc/tempo/tempo.yml
    command: -config.file=/etc/tempo/tempo.yml
    ports:
      - "3200:3200"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
