version: "3.8"

services:

  sample-app:
    build: ./sample-app
    container_name: sample-app
    volumes:
      - ./sample-app:/app
      - ./logs:/var/log
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml
    command: -config.file=/etc/loki/loki.yml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml
      - ./logs:/var/log
    command: -config.file=/etc/promtail/promtail.yml

  tempo:
    image: grafana/tempo:latest
    volumes:
      - ./tempo/tempo.yml:/etc/tempo/tempo.yml
    command: -config.file=/etc/tempo/tempo.yml
    ports:
      - "3200:3200"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

  backend:
    build: ./relaiablity-studio/backend
    container_name: reliability-backend
    ports:
      - "9000:9000"
    depends_on:
      - prometheus
      - loki
      - tempo

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=sarika-reliability-studio-app
    volumes:
      - ./relaiablity-studio:/var/lib/grafana/plugins/reliability-studio
    depends_on:
      - prometheus
      - loki
      - tempo
      - backend
